### ISSUE TITLE
Support YAML 1.2 via snakeyaml-engine

### ISSUE THREAD

**Issue by Flowdalic** [losizm/shampoo#1]
I am looking for YAML 1.2 compatibility. It appears that the successor of snakeyaml, snakeyaml-engine supports this. Please consider adding support for, or switching to, snakeyaml-engine. Thanks.

**Comment by losizm** [comment]
Considered &ndash; Look for update in coming weeks.

Thanks for your interest.

**Comment by Flowdalic** [comment]
Thank you very much for your reply.
 
I am currently evaluating YAML libraries for Scala. My requirements are
1. Scala 3 support
2. YAML 1.2 support (which would be supported by building on top of snakeyaml-engine)
3. Strict parsing, that means invoke a callback, which potentially reports a failure, if an unknown YAML element is encountered
4. Proper `Option` handling


Unfortunately, there doesn't seem to be a library that meets all requirements. For example https://github.com/VirtusLab/scala-yaml has non-intuitive Option handling and [simply ignored unknown YAML entries](https://github.com/VirtusLab/scala-yaml/discussions/242).

Maybe shampoo could be the YAML library I am looking for. :)

**Comment by losizm** [comment]
Shampoo 0.2.0 switches to [SnakeYAML Engine](https://github.com/snakeyaml/snakeyaml-engine/).

In regards to your requirements:

1. Source is compiled with Scala 3.3.1.
2. YAML 1.2 is supported per SnakeYAML Engine 2.7.
3. [load()](https://losizm.github.io/shampoo/0.2.0/api/shampoo/yaml/Yaml$.html#load-54c) reads the entire YAML input and constructs a [YamlNode](https://losizm.github.io/shampoo/0.2.0/api/shampoo/yaml/YamlNode.html). Custom validation logic should be encapsulated in [YamlConstructor[T]](https://losizm.github.io/shampoo/0.2.0/api/shampoo/yaml/YamlConstructor.html) when reconstructing `YamlNode` to `T`.
5. [readOption\[T\]()](https://losizm.github.io/shampoo/0.2.0/api/shampoo/yaml/YamlMapping.html#readOption-fffff0de) constructs `Some[T]` if key is defined and its associated value is not `YamlNull`; otherwise, `None` is returned.

**Comment by Flowdalic** [comment]
> Shampoo 0.2.0 switches to [SnakeYAML Engine](https://github.com/snakeyaml/snakeyaml-engine/).
> 
> In regards to your requirements:

Thanks for your work. Much appreciated.

Unfortunately, I found another requirement:

Implicit, typically reflection-based, parsing. That is, on the example of scala-yaml, simply make the case class extends `YamlDecoder` which enables the YAML library to automatically parse a YAML string into the case class **without** having to explicitly specify the decoder for it.

Is something like this planed? Should I create an issue for it?

**Comment by losizm** [comment]
Shampoo is "a general solution to a specific problem."

It avoids decorating classes with traits that may be irrelevant (and conflicting) in general use. This is the same approach taken by [Grapple](https://github.com/losizm/grapple/), which is the JSON equivalent to Shampoo.

That said, I'll consider a solution to [type class derivation](https://dotty.epfl.ch/docs/reference/contextual/derivation.html).

Stay tuned.
